server:
  port: 8082

spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/list-keep
  jpa:
    show-sql: true
